### ISSUE TITLE
AndroidManifest minSdkVersion = 24

### ISSUE THREAD

**Issue by QiXi** [eygraber/compose-color-picker#253]
My project is limited to a minimum of API 23 and the library has a limit of 24 API. Does it make sense to use version 24 depending?
> Manifest merger failed : uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [com.eygraber:compose-color-picker-android-debug:0.0.14] /AndroidManifest.xml as the library might be using APIs not available in 23

**Comment by eygraber** [comment]
I don't think we're using anything API 24. I'll look into dropping the minApi.
